### ISSUE TITLE
Faceblur

### ISSUE THREAD

**Issue by pjebs** [esimov/pigo-wasm-demos#2]
For Faceblur demo, you should add some lag to the filter if the face-detection fails to discover a face.

i.e. If no face is detected, for a short period of time, assume the location of the face is the same as before and still apply the filter.

**Comment by esimov** [comment]
I understand what you mean, but your suggestion implies that in case no face is detected to freeze up the frame for a certain period of time, this is something I would like to avoid. I better approach would be to blur out the whole stage in case no face is detected.
