### ISSUE TITLE
access to localhost was denied

### ISSUE THREAD

**Issue by ttys000** [esimov/pigo-wasm-demos#3]
### What did I do?

run the following commands:

```bash
$ go install github.com/esimov/pigo-wasm-demos@latest
package github.com/esimov/pigo-wasm-demos: build constraints exclude all Go files in /Users/xxx/go/pkg/mod/github.com/esimov/pigo-wasm-demos@v0.0.0-20221114092220-a4dc87888bb4
$ git clone git@github.com:esimov/pigo-wasm-demos.git
......
$ cd pigo-wasm-demos
$ make demo1
cp -f "$(go env GOROOT)/misc/wasm/wasm_exec.js" ./js/
GOOS=js GOARCH=wasm go generate
GOOS=js GOARCH=wasm go build -o lib.wasm "masquerade.go"
open 'http://localhost:5000'
go run server/init.go
2022/11/30 11:24:34 serving /Users/xxx/pigo-wasm-demos on localhost:5000
```

### What happened?

<img width="997" alt="image" src="https://user-images.githubusercontent.com/12792995/204700439-9f7c3b18-c90e-4ca3-9e1c-0e67f12505f8.png">

### What I expected to happen?

demo1 running correctly.

### Environment

- Device: MacBook Pro M1
- OS: macOS Ventura, Version 13.0.1
- Browser: Microsoft Edge, Version 107.0.1418.56 (Official build) (arm64)
- Go Version: go1.19.3 darwin/arm64

**Comment by esimov** [comment]
If you try to run the following command directly does it give you any kind of errors? 

```bash
$ GOOS=js GOARCH=wasm go build -o lib.wasm "masquerade.go"
```
If not try to hard reload the browser window with `CTRL-R`.

**Comment by ttys000** [comment]
No errors are running the go build command, `CTRL-R` does not change anything. 

I can get the correct response with `curl`, I am still working on this.

**Comment by ttys000** [comment]
I found the root cause and can play the demos now.

Port 5000 is actually used by Control Center (AirPlay service) in macOS from Monterey, so the browser will return 403 if you try to access it, but the `curl` is not affected by this somehow.

If I try to use ports like 6000 or 6666, the browser will return an `err_unsafe_port` error, that's because [there are some ports are blocked.](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/net/base/port_util.cc#27)

We should either use an unblocked port or add the `--explicitly-allowed-ports` option to the browser startup command.

**Comment by ttys000** [comment]
FYI:
https://developer.apple.com/forums/thread/682332
https://jazzy.id.au/2012/08/23/why_does_chrome_consider_some_ports_unsafe.html
